name: Build Flutter APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Remove pubspec.lock
        run: |
          rm -f pubspec.lock
          rm -f example/pubspec.lock

      - name: Get dependencies (package)
        run: flutter pub get

      - name: Get dependencies (example)
        run: |
          cd example
          flutter pub get

      - name: Build APK
        run: |
          cd example
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: example/build/app/outputs/flutter-apk/app-release.apk
